App\Entities\Product\File:
  table: product_files
  primaryKey: id
  props:
    id:
      field: id
      isEntity: false
      type: int
    product:
      type: App\Entities\Product
      isEntity: true
      foreignKey: product_id
      relationType: one_to_many
      inversedBy: files
      field: product_id
      rule: 'required'
    name:
      field: name
      isEntity: false
      type: string
      rule: 'required|max:255'
    type:
      field: type
      isEntity: false
      type: string
      rule: 'required|max:25'
    extension:
      field: extension
      isEntity: false
      type: string
      rule: 'required|max:10'
    size:
      field: size
      isEntity: false
      type: int
      rule: 'required'
    createdBy:
      field: created_by
      isEntity: false
      type: string
      rule: 'max:255'
    updatedBy:
      field: updated_by
      isEntity: false
      type: string
      rule: 'max:255'
    createdAt:
      field: created_at
      isEntity: false
      type: DateTime
    updatedAt:
      field: updated_at
      isEntity: false
      type: DateTime
