App\Entities\ProductCategory:
  table: product_categories
  primaryKey: id
  props:
    id:
      field: id
      isEntity: false
      type: int
    productCategoryMappings: 
      type: App\Entities\Product\ProductCategoryMapping
      isEntity: true
      foreignKey: prodyuct_category_id
      relationType: many_to_many
      inversedBy: productCategory
      field: produuct_category_id
      rule: 'required'
    name:
      field: name
      isEntity: false
      type: string
      rule: 'required|max:255'
    description:
      field: description
      isEntity: false
      type: string
      rule: 'max:255'
    shop:
      type: App\Entities\Shop
      isEntity: true
      foreignKey: shop_id
      relationType: one_to_many
      inversedBy: products
      field: shop_id
      rule: 'required'
    createdBy:
      field: created_by
      isEntity: false
      type: string
      rule: 'max:255'
    updatedBy:
      field: updated_by
      isEntity: false
      type: string
      rule: 'max:255'
    createdAt:
      field: created_at
      isEntity: false
      type: DateTime
    updatedAt:
      field: updated_at
      isEntity: false
      type: DateTime
